version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: nest_pg
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-net

  app:
    container_name: nest_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file: .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    networks:
      - nest-net
    volumes:
      - .:/app
    command: yarn start:dev

volumes:
  pgdata:

networks:
  nest-net:
    driver: bridge
